spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://localhost:3306/network-management
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: development
  h2:
    console:
      enabled: true
      path: /h2-console